version: '3.4'

services: 
    database:
        image: mysql:8.0.19
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root@karta0898098
        ports: 
            - "8081:3306"
        volumes: 
            - ./sql:/docker-entrypoint-initdb.d
            - ./data:/var/lib/mysql
    redis:
        image: "redis:alpine"
        
        command: redis-server --requirepass KwEQPjrj7wGxCr3q
        
        ports:
            - "8082:6379"

    fake-product-services:
        build: .
        depends_on: 
            - database
            - redis
        ports: 
            - "8080:8080"
        environment: 
            TZ: Asia/Taipei
            REDIS-ADDRESS: redis:6379
            REDIS-PASSWORD: KwEQPjrj7wGxCr3q
            DB_CONNECTION_STRING: root:root@karta0898098@(database:3306)/fake_product?charset=utf8&parseTime=True&loc=Local